### ISSUE TITLE
barista does not support a "bare" route

### ISSUE THREAD

**Issue by katanacrimson** [kieran/barista#35]
As on tin. I'd expect that a router should be able to handle a "/" route, just for convenience's sake.

At the very least, I'll try to abuse .defer for now to get things working.

**Comment by kieran** [comment]
You can do this:

``` coffeescript
router.get '/'
.to 'Main.index'
.as 'home'
```

Example: 
![screen shot 2015-03-20 at 11 27 09 pm](https://cloud.githubusercontent.com/assets/3444/6763577/be77c33e-cf58-11e4-94dc-d34bce4f91ed.png)

Does that work for you?

P.S. You can play around with barista here: http://kieran.github.io/barista/
